### ISSUE TITLE
Suggest adding feeds from pages

### ISSUE THREAD

**Issue by adomasven** [adomasven/zotero#10]
See
http://mxr.mozilla.org/mozilla-central/search?string=addFeed&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=mozilla-central
http://mxr.mozilla.org/mozilla-central/search?string=addLiveBookmark&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=mozilla-central

**Comment by dstillman** [comment]
Closed by https://github.com/zotero/zotero/commit/5b8d3c178fca0788288b4ebd7a7dcd763b92c6d0
