### ISSUE TITLE
Porting BBT to 5.0: error in Zotero.Translators.reinit()

### ISSUE THREAD

**Issue by retorquere** [adomasven/zotero#13]
I'm getting this error:

```
[JavaScript Error: "Error(s) encountered during statement execution: no such column: fileName [QUERY: SELECT fileName, metadataJSON, lastModifiedTime FROM translatorCache] [PARAMS: ] [ERROR: no such column: fileName]" {file: "chrome://zotero/content/xpcom/db.js" line: 694}]
```

**Comment by adomasven** [comment]
What is the output of `SELECT * FROM version;` on your sqlite database? It seems like a database migration did not go through properly when you launched 5.0 with a 4.0 database.

**Comment by retorquere** [comment]
Apologies, some code of mine got executed before the call to `yield Zotero.
