### ISSUE TITLE
Feed item translation UX

### ISSUE THREAD

**Issue by adomasven** [adomasven/zotero#5]
Regarding https://github.com/adomasven/zotero/tree/feature/feed-translation

We have translation of feed items on drag now. However:
1. It is non-deterministically broken when dragging onto collections (libraries are fine). @dstillman mentioned translation might be broken in 5.0, but I am using essentially the same mechanisms as `Zotero.Browser.scrapeThisPage`, so it may not be my fault. Also, for some feeds it works fine.
2. There is no indication that the drag was successful/is happening, as translation occurs in the background and items get added asynchronously. We need some sort of loading/happening animation or something, but I am not sure what. We could show a popup, similar to the one when a file from the web is being scraped.

Feed items now also get translated on selection in the feed view, which causes problem with them being reordered. This is because many feeds do not have publication date set and if they do, they do not have the time, which means that loads of feed items have the same data for Date Added field. When a translation occurs, new secondary data is added (like author names), which causes a reordering. I am thinking it may be a good idea to store feed item order as seen in XML, so we have some unchanging field to sort on.

Before traslation:
![image](https://cloud.githubusercontent.com/assets/5899315/12760431/4b30aaa4-c9de-11e5-849c-d2d720a39916.png)
After some translations:
![image](https://cloud.githubusercontent.com/assets/5899315/12760475/718f628a-c9de-11e5-97cc-b270a2f38b0c.png)

Suggestions and proposals are needed.

**Comment by dstillman** [comment]
I'll take a look at the translation part. Make sure you've rebased against the latest master.

The popup we use for saving from the web could work, but you could drag hundreds of items at once, right? We could start with that one, at least.

I'll try out the branch and take a look at sorting. It seems like sorting by feed order by default would be good. Not totally sure how to do that in the UI, though — we could have an implicit sort and no selected column, but then there's not even the ability for the user to choose asc or desc for the default sort, which seems important.

**Comment by dstillman** [comment]
OK, haven't looked at the code yet, but trying it out this is really great so far.

On dates:

> many feeds do not have publication date set and if they do, they do not have the time, which means that loads of feed items have the same data for Date Added field

With Nature, I'm seeing Date Added as the time the item was added to the database and Date Modified as the publication date from the feed, but with a timestamp, meaning that in -0500 that ends up as 7 p.m. the day before for everything. Is Date Added supposed to be the DB date? Nature seems to have `prism:publicationDate` available.

In any case, seems like we have two options:

1) Make them both DB dates.

2) Make them both feed dates (when possible).

The first is easier and more consistent with standard Zotero behavior, but not particularly interesting to the user and kind of weird in the context of a feed. And if you happen to have those columns shown, it's sort of dumb to see all the repeated dates. (Same problem in normal Zotero usage with mass-imported data, but with web-imported data you at least get meaningful different dates.)

The second works well for Atom, which has separate `published` and `updated` fields that generally pertain to the feed entry itself — that would make this basically a view through to the feed. It seems weirder for RSS 1, where `prism:publicationDate` is generally (or at least in Nature's feeds) describing the underlying resource. Not sure how `pubDate` in RSS 2 is used.

Other issues with the second approach:
- For RSS, Added and Modified would both be set on the first retrieval, and if the pub date changed, Modified would get updated but Added wouldn't
- A time portion is currently required for both DB fields, so either we have to change that for feed item dates or, if there was only a date in the feed, we'd need to store as 00:00:00 and hide the time portion on display. But then we'd have the problem of a genuine 00:00:00 time in the feed.
- We'd need to use retrieval date as a fallback if there was no publication date (and then account for a possible date with timestamp paired with entries without timestamps, though presence of pub date is probably usually consistent within a feed?).
- For RSS, Date Added/Modified would almost always (?) be equivalent to the Date field. (I'm not sure how you're handling `dc:date` vs. `prism:publicationDate`, or if there's even supposed to be a difference in meaning.) I guess it's still sort of a view through to the feed, but it seems sort of pointless, and makes less sense with the "Date Added"/"Date Modified" labels than it does with Atom.

To discuss.

**Comment by adomasven** [comment]
> With Nature, I'm seeing Date Added as the time the item was added to the database and Date Modified as the publication date from the feed, but with a timestamp, meaning that in -0500 that ends up as 7 p.m. the day before for everything. Is Date Added supposed to be the DB date?

Generally the date handling is kind of hairy. Mainly, because the XPCOM feed reader provides its own fields `feedEntry.published` and `feedEntry.updated` with no documentation where those values would usually come from. The code tries to do the most reasonable thing, and sets `date` field to `feedEntry.published`, and then falls back to `dc:date` and `prism:publicationDate`, whichever available. `dateModified` is sampled from `feedEntry.updated` and falls back to `feedEntry.published` or is left empty. `dateAdded` is the DB date

> - We'd need to use retrieval date as a fallback if there was no publication date (and then account for a possible date with timestamp paired with entries without timestamps, though presence of pub date is probably usually consistent within a feed?).
> - For RSS, Date Added/Modified would almost always (?) be equivalent to the Date field. (I'm not sure how you're handling dc:date vs. prism:publicationDate, or if there's even supposed to be a difference in meaning.) I guess it's still sort of a view through to the feed, but it seems sort of pointless, and makes less sense with the "Date Added"/"Date Modified" labels than it does with Atom.

Yeah, the general problem is that although the usage of date fields within feeds will be consistent, across feeds it can differ, including stuff like feeds refusing to follow any reasonable standards whatsoever (see [IEEExplore](http://ieeexplore.ieee.org/search/searchresult.jsp?searchField%3DSearch_All%26queryText%3Dwater&searchOrigin=saved_searches&rssFeed=true&rssFeedName=water)) or simply not including any date information (aside from feed date) for their items (see [arxiv](export.arxiv.org/rss/astro-ph)).

Overall I would say in feeds the Date Added and Date Modified fields are not meaningful (aside from Date of publication of the actual item). We could probably go as far as just not displaying Date Added and Date Modified fields for feeds completely. We can still use Date, which ideally would indicate the publication date of an item in the feed, sampled from `dc:date`, `prism:publicationDate` and `pubDate`, but given some feeds won't have them and some will provide the date the item was added to the feed, rather than got published, I think it's better to stay away too. Main reasoning for this is the reduction of forum questions, bound to come up, when feeds from different sources have very different date values.

I think it makes sense to add a `#` field for natural feed order, with values [1 - n], which would allow to sort ascendingly or descendingly. This would also mean that we don't lose the ability sort on other fields when needed.

So my proposal is:
- Do not display any date fields for feed items. Display Date after translation
- Add a `#` field for natural sort order, only displayed in feeds.

**Comment by adomasven** [comment]
After additional discussions on IRC, we have arrived at this plan:
- Date Added and Date Modified follow standard DB conventions
- Date field is the best guess from `{dc:date, prism:publicationDate, pubDate, published, updated}`. Field gets updated after translation.
- Feeds sorted by natural order and changing sort order by clicking on column headers is disallowed to prevent translation making items bounce around the list. Desc/asc sort controlled in settings.

For translation indication, we will use standard popup. Will go for something else if it's not appropriate/sufficient.

**Comment by adomasven** [comment]
Implemented and merged with 6c43e75d269f2a5a165ced63ab1aeaf28f0bcf04
